export const status=["Active", "Inactive"]
export const statusProject = [, 'All', "In progress", "Under Review", 'Completed',' To Do']
export const designation=["Maneger", "Team Lead", "Tester", "Jr. Developer", "Sr. Developer"]
export const view=["Card", "List"]
export const projectSortConstant=["Project Name", "Team"]
export const departmentOptions=["IT", "Marketing"]
export const taskView =["List", "Kanban"]
export const projectPriority =["High", "Low", "Medium"]
